# If you come from bash you might have to change your $PATH.
export PATH=$PATH~/bin:/usr/local/bin:/usr/local/sbin
export PATH="/usr/local/bin:$PATH"
export PATH="/Users/Lukas/Library/Python/3.7/bin:$PATH"

# add openssl to path
export PATH="/usr/local/opt/openssl/bin:$PATH"

# add openssl for compilers
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

# LLVM variables for path and compilers
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"

# adding cabal/bin to Path for Haskell
export PATH="$HOME/Library/Haskell/bin:$PATH"

# adding crosscompile for beaglebone to path
 export PATH="$HOME/.crosscompile/bin:$PATH"

# added by Miniconda3 4.3.21 installer
# export PATH="$PATH:/Users/Lukas/Developer/miniconda3/bin"

# add anaconda3
export PATH="$PATH:/Users/Lukas/anaconda3/bin"

# setting java_home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home

# gradle 3.0 setup for sopra (university project)
# setting GRADLE_HOME
export GRADLE_HOME=/Users/Lukas/Documents/Universität/3.Semester/Sopra/Gradle_3.0

# setup for BSc_thesis repo with tensorflow, protobuf and eigen3
# tensorflow path
export PATH_TENSORFLOW="/Users/Lukas/Documents/Universitaet/Bachelor/Semester_6/Bachelor_Arbeit/dependencies"
# protobuf path
export PATH_PROTOBUF="/Users/Lukas/Documents/Universitaet/Bachelor/Semester_6/Bachelor_Arbeit/dependencies"
# eigen path
export PATH_EIGEN="/Users/Lukas/Documents/Universitaet/Bachelor/Semester_6/Bachelor_Arbeit/dependencies"

# add lab path to pythonpath
# export PYTHONPATH="/Users/Lukas/Documents/Universitaet/Bachelor/Semester_6/Bachelor_Arbeit/lab"

# used for tensorflow scripts
export PATH="/Users/Lukas/Library/Python/3.6/bin:$PATH"
export PATH="/Users/Lukas/Library/Python/2.7/bin:$PATH"

# add StarCraft 1.16.1 Path to MPQ files for TorchCraft
export OPENBW_MPQ_PATH="/Users/Lukas/.wine/drive_c/Program Files/StarCraft_1.16.1"

# add dependencies tensorflow to PYTHONPATH
# export PYTHONPATH="${PYTHONPATH}:/Users/Lukas/Documents/Universitaet/Bachelor/Semester_6/Bachelor_Arbeit/dependencies/tensorflow_source/tensorflow"

# init rbenv for ruby rbenv
eval "$(rbenv init -)"

# Setup terminal, and turn on colors
export TERM=xterm-256color
export CLICOLOR=1

# Enable color in grep
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'

# # Additional scripts
source ~/dotfiles/scripts/functions.zsh 
source ~/dotfiles/scripts/stream/selectstreams.sh
source ~/dotfiles/scripts/stream/streams.sh

# ------------------------------------ OH - MY - ZSH ------------------------------------

# Path to your oh-my-zsh installation.
export ZSH=/Users/Lukas/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-256color)

source $ZSH/oh-my-zsh.sh

setopt no_beep
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'
# Use Ctrl - space for completion
bindkey '^ ' autosuggest-accept

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor
export EDITOR='vim'
export VISUAL='vim'


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/Lukas/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/Lukas/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/Lukas/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/Lukas/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

